name: Simple manual workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: 
           echo 'I am running a job in the PROD environment'
  Dev:
    runs-on: ubuntu-latest
    environment: Dev
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: 
          echo 'I am running a job in the PROD environment'    
  QA:
    runs-on: ubuntu-latest
    environment: QA 
    needs: Dev
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run:
          echo 'I am running a job in the PROD environment'    
  Prod:
    runs-on: ubuntu-latest
    environment: Prod 
    needs: QA
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: 
          echo 'I am running a job in the PROD environment'    
